#! /usr/bin/env bash

# =================================================================
#
# Work of the U.S. Department of Defense, Defense Digital Service.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -eu

# move up a directory
cd "${DIR}"/..

pkgs=$(go list ./... | grep -v /vendor/ | tr "\n" " ")

check_command () {
  cmd=$1

  if ! command -v "bin/${cmd}" > /dev/null; then
    echo "Missing ${cmd}, please install into bin/ directory with 'make bin/${cmd}'"
    exit 1
  fi
}

# Validate that the commands exist
check_command errcheck
check_command misspell
check_command shadow
check_command staticcheck

echo "******************"
echo "Running go vet"
go vet $pkgs
echo "******************"
echo "Running go vet with shadow"
go vet -vettool="bin/shadow" $pkgs
echo "******************"
echo "Running errcheck"
bin/errcheck ${pkgs}
echo "******************"
echo "Running staticcheck"
bin/staticcheck -checks all ${pkgs}
echo "******************"
echo "Running misspell"
bin/misspell -locale US -error *.md *.go
